### ISSUE TITLE
Gapless works ?

### ISSUE THREAD

**Issue by PascalBad** [KenT2/pipresents-gapless#22]
Hello.
First of all, I thank you a lot for your work. It's wonderful. Furthermore your manual is excellent. And excuse me for my poor english (I'm french).
I maked a very simple show based on radiobuttonshow.
There's a summary looping video. Via GPIO, I can choose some other videos. When these videos ended, it returns to summary video. All videos are fullscreen.
When I use freeze at end in track option, there is a black screen for half a second in every transition.
When I use seamless loopin track option of summary track (and disable freeze at end) , there is a gray screen between the first loop at each return to summary. For next loops it's ok.
What do you think of these issues ?
I have made a very updated installation of all. Rasperry pi 3 with Jessie and pipresents 1.3.1h. GPU at 256. All videos are mp4 and 1920x1080.

**Comment by KenT2** [comment]
Hi
Gapless is more of a name than a statement that I have removed all the gaps sorry ;-(

A mediashow will not have gaps at the end of videos because freeze at end covers up the gaps by pausing the video while the next track loads. However in a radiobuttonshow you are stopping a video rather than ending it naturally and there is no pause in this situation. I could add a pause but in a museum situation I thought it not essential, and its difficult to implement.

The grey flash on seamless loop is an omxplayer issue. See 

https://github.com/popcornmix/omxplayer/issues/425

It looks like it has been fixed after the May 16 Raspbian download so its worth doing a sudo apt-get update sudo apt-get upgrade

**Comment by PascalBad** [comment]
Hi Ken,
Many thanks for your fast answer.
I tried a lot of things.
I saw in your link that the new version of omxplayer doesn't goes with a sudo apt-get upgrade. So I built it. But it doesn't work better. Finally, it seems there's no issue with a longer video.
I tried a mediashow respect to your indication with a medialist of 3 videos continuous but the freeze don't work again. I wonder if it is because of the codec.
I'm going to try with anothers videos.

**Comment by KenT2** [comment]
[previous text deleted as not answering the question]
Reading your posts again it appears you are concerned with half a second gap between videos. 

The effect of 'freeze at end' is to bring the black gap down from a second or so to less than half a second.  Pi Presents is unlikely to achieve better than this. Seamless looping of one track is better.

PP achieves this small apparent gap by freezing a frame of the video near the end to cover up the black gap while the next video loads. The artmediashow reduces the gap to cover up by pre-loading the next video while the first is playing. There is still a small gap and 'freeze at end' is required to cover this up'.

**Comment by PascalBad** [comment]
I'm not sure I understood what you said.
I tried an artmediashow with my videos. Between tracks (with freeze at end), I've got some black frames (I think about 1/4 second).
Otherwise, I haven't issue with seamless loop since I use video more than 40s.
