### ISSUE TITLE
Support for more IO than native RPi

### ISSUE THREAD

**Issue by IgorvanDame** [KenT2/pipresents-gapless#28]
I'm working on enabling audio on new museum exhibits that are triggered by 16 illuminated buttons. I am able to communicate with two ArduinoMega2560s using Firmata (PyMata) successfully (16 buttons, 16 button lights, 16 outputs for relays to trigger spots on exhibits). I would like to use PiPresents to serve the audio files (and video lyrics) for the exhibit but your gpiodrivers.py appears to be locked into the RPi gpio architecture.
1) Should I be creating a replacement gpiodrivers.py file including import of serial and firmata or wiredpi etc.?
 or
2) Are you actively providing support for I2C, SPI, or CanBus for creating more triggers for pipresents?

Where is the RPi GPIO architecture first defined in your program?
Is this as simple as adding the import statements to implement the PyMata PySerial libraries?

Any guidance that would help me enable the application for multiple external IO would be welcomed.

**Comment by KenT2** [comment]
People who have implemented this type of thing so far have connected gpio lines from the Arudino to the Pi. Your method is just as valid. My only concern would be if gpiodriver.py were extended to do some hard real time processing, such as reading a RFID card directly, then there could be delays due to periods of heavy CPU usage by PP, for example rendering an image. I don't know enough about Linux to know whether this is a problem or not.

You should be creating a replacement gpiodriver.py file.

I will  probably never provide support for interfaces other than gpio as there are so many different possibilities. What I will do one day in the future is to enable people to write their own and then register them with Pi Presents. I would be interested in any code you produce so that one day I can turn it into an IO plugin in the new architecture.

The current interface with gpiodriver .py is something like this

In pipresents.py 
   The prescence of gpio.cfg is detected to enable gpio
    GPIODriver is initilised by init() and then call poll() to start the gpio sampliing
The initialisation has a callback function which gpiodriver.py uses to return an event with a symbolic name when a change of input is detected
Association of pins to symbolic names is in the gpio.cfg

For output 
commands like 'out1 state on' (symbolic name, parameter type, value) are received by gpiodriver.py handle_output_event().

The long term aim is that the output command hides the implementation of the output from the core of PP. So 'out1 state' could result in a gpio output or sending a message via serial link depending on gpio.cfg.

There are a few extras for shutting down cleanly etc.
