### ISSUE TITLE
No sound from audio tracks when using alsa

### ISSUE THREAD

**Issue by KenT2** [KenT2/pipresents-gapless#44]
Continued from #42 

@mortomanus

Am I correct in saying that you were trying to use an alsa device with an audio track.

Currently PP does not allow for alsa devices in audio tracks, but it does seem possible.  I do not have an audio device so I need your advice

Currently the code in pp_audiodriver.py line 289 is 

`            if self.mplayer_audio != "":
                if self.mplayer_audio == 'hdmi':
                    os.system("amixer -q -c 0 cset numid=3 2")
                else:
                    os.system("amixer -q -c 0 cset numid=3 1")   `

Can introduce an 'Audio Player Audio' value of alsa and  change this in any way?

Secondly did you try the hdmi value and  set hdmi_drive=2 in config.txt, tht has worked for me.

**Comment by mortomanos** [comment]
The main problem was that it worked already, but I heard nothing because the mixer was set to -102dB. What helped was `amixer cset numid=1 0` to have the volume level adjusted.
Regarding the question for the device: I'm just using the internal sound device. But I can use the alsa mixer for setting values.
Regarding the question for hdmi_drive: yes, I did this already.
