### ISSUE TITLE
Return to liveshow from menu

### ISSUE THREAD

**Issue by martinschultzkristensen** [KenT2/pipresents-gapless#80]
Hi,

I have a liveshow to loop as an intro for the user. When input, pp goes to the menushow. When a track is selected in the menushow, I want it play single-run, and the **return to the liveshow loop.**

Is this possible?

Thanks!

**Comment by KenT2** [comment]
Use the exit command rather than stop.

**Comment by martinschultzkristensen** [comment]
Hey Ken.

I tried, but it still doesn't do what I want. I forgot to mention that I want it **automatically** to return to the liveshow loop.
E.g. I choose a video from the menu, and when it is done, it takes me to the liveshow.

Is it my lack of skills? -Course I've tried to change in the controls pp-exit exit (as many place as I could.)

Thanks for your help.

**Comment by KenT2** [comment]
I wonder if your change should have been pp-stop exit. You need to keep the symbolic name of the event the same and change the command from stop to exit.

However the above will not solve your automatic problem. The solution is not intuitive, even I had to think about it.
 What you need is to start a radiobuttonshow from the Start Show and make its 'first' track a show track which will reference the liveshow.
I suggest you start with the pp_radiobuttonshow_1p3 example and change the first track from the image to a show track.

**Comment by martinschultzkristensen** [comment]
Thanks for the answer.
pp-stop exit was nice to get an understanding off.

I quickly want to bust in here and say: I (ideally) want it to be **Menu**. Do you think the same procedure is possible? I'm going to give it a try now! 

I just got the radiobuttonshow to work like you predicted!

**Comment by KenT2** [comment]
Using a menu as the First track of a radiobuttonshow will not work as you need to display the menu in order to control it, (and PP will not be happy)

You will need to revert to your first idea, a liveshow with the menushow as a child track. Using the exit command will get you back from a track played from the menushow to the liveshow.
 
In order to execute the exit command automatically at the end of each track of the menu add the control 'pp-exit exit' to the menushow then in the 'Show Control at End' field of each track of the menushow (except menu-track) add 'event pp-exit'. This will generate an input event.

You can of course associate pp-exit with a key in a keys.cfg if you want the user to terminate the tracks early.

I'm quite chuffed, you have discovered the first real use for the event Show control command. I implemented it because I could; without being able to think of a reason for it.

**Comment by martinschultzkristensen** [comment]
That's what I love about PP, it's trying to be as versatile as possible without to complicated. 🥇 

Your instructions worked great, Thanks! -Now is where I'm getting difficult (sorry!):

I actually want each track of the menushow to be a child(menu)show, each with 2 tracks:
1) Discription of show
2) Play show

*Discription of show* is easy be course it's a looped promovideo (with some background text/image), and the user exits out of this when they have obtained sufficient information. (This I have succeeded.)
*Play show* is the one that troubles me:
When the child(menu)show has control 'pp-exit exit', and track *play show* has 'Show Control at End' = 'event pp-exit' it unfortunately only takes me to the parent menushow (and not all the way up to my liveshow).
I tried to add 'event pp-exit' in the child(menu)show's 'Show Control at End' field, and PP did not like that **AT ALL!!!** 

**If you know of a way to do this I'm very curious. Also if you're thinking of an alternative creative one.**

If you are thinking *"Is this guy serious, or is he just looking for ways to mess with PP"*, then this is the project I want to run with a RPi: [https://vimeo.com/250489328](url)

**Comment by KenT2** [comment]
make the mediashow that is your menu item 'Single Run'. In the 'Show Control at End' field of the mediashow add 'openexclusive liveshow'

This will close all the shows and then open the top level liveshow. 

There might be a bug because openexclusive did not close the mediashow, hence it needs to be single run, not repeat.

Your not messing with PP, I need people to pose hard questions so I can detect limitations and improve the system.

**Comment by martinschultzkristensen** [comment]
Fantastic! I got it to work, thanks to your help.
It seems like it's working fine, but I have only run it very shortly.

Now the next thing for me would be the sound for each joystick/button action, but I think I have an idea of how to get that covered. Otherwise I'll open a new repository. 😉 
All the best!
Thanks!!!
